spring:
  datasource:
    url: jdbc:mysql://cdb-e4a6q0m8.cd.tencentcdb.com:10006/cinema?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: huangyulong123--
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
  application:
    name: cinema-m
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  #Elasticsearch配置
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
  #redis配置
  redis:
    host: 148.70.167.3
    port: 6666
    password: 123
    database: 1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  support-methods-arguments: true
  params: pageNum=currentPage,pageSzie=pageSize
  helper-dialect: mysql
logging:
  level:
    com.woniu.woniuticket.cinema.dao: debug
server:
  port: 8081
ImgUploa_folder: /static/img/
#注册中心注册
eureka:
  client:
    service-url:
      defaultZone: http://106.52.231.180:8761/eureka,http://106.52.231.180:8762/eureka
#内网穿透配置
  instance:
    hostname: 263g03u837.wicp.vip:35981
    status-page-url: http://${eureka.instance.hostname}
    instance-id: http://${eureka.instance.hostname}
    ip-address: ${eureka.instance.hostname}
#微服务访问feign
feign:
  hystrix:
    enabled: true
#shiro配置
#ribbon:
#  ConnectTimeout: 1000
#  ReadTimeout: 1000
#zull:
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 10000
