spring:
  datasource:
    url: jdbc:mysql://106.52.231.180:3306/cinema?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
  application:
    name: cinema-m
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  support-methods-arguments: true
  params: pageNum=currentPage,pageSzie=pageSize
  helper-dialect: mysql
logging:
  level:
    com.woniu.woniuticket.cinema.dao: debug
server:
  port: 8081
ImgUploa_folder: /static/img/
eureka:
  client:
    service-url:
      defaultZone: http://106.52.231.180:8761/eureka,http://106.52.231.180:8762/eureka
  instance:
    hostname: q2632h0347.zicp.vip:47853
    status-page-url: http://${eureka.instance.hostname}
    instance-id: http://${eureka.instance.hostname}
    ip-address: ${eureka.instance.hostname}
feign:
  hystrix:
    enabled: true
